---
# tasks file for nginx-site-removal

- name: "Remove Nginx site configs"
  file: 
    state: absent
    path: /etc/nginx/conf.d/{{ item.name }}.conf
  with_items: '{{ nginx_site_removal_sites_to_remove }}'
  notify: "restart nginx"

- name: "Remove Certbot SSL live files"
  file: 
    state: absent
    path: /etc/letsencrypt/live/{{ item.url }}
  with_items: '{{ nginx_site_removal_sites_to_remove }}'
  ignore_errors: yes

- name: "Remove Certbot SSL renewal files"
  file: 
    state: absent
    path: /etc/letsencrypt/renewal/{{ item.url }}.conf
  with_items: '{{ nginx_site_removal_sites_to_remove }}'
  ignore_errors: yes

- name: "Remove Certbot SSL archive files"
  file: 
    state: absent
    path: /etc/letsencrypt/archive/{{ item.url }}
  with_items: '{{ nginx_site_removal_sites_to_remove }}'
  ignore_errors: yes

- name: "Find all Nginx logs"
  find:
    paths: /var/log/nginx
    patterns: "{{ item.name }}.*"
  with_items: '{{ nginx_site_removal_sites_to_remove }}'
  register: files_to_delete

#- name: "Debugging files_to_delete variable"
#  debug:
#    var: files_to_delete

- name: "Remove Nginx logs"
  file: 
    state: absent
    path: "{{ item.path }}"
  with_items: "{{ files_to_delete.results[0].files }}"

#- name: "Remove sites-available Nginx configuration for {{ item.name }}"
#  file: 
#    state: absent
#    path: /etc/nginx/sites-available/{{ item.name }} 
#  with_items: '{{ nginx_site_removal_sites_to_remove }}'
#  notify: "restart nginx"

- name: "Remove site directories under webserver document root"
  file: 
    state: absent
    path: "{{ nginx_site_removal_web_home }}/{{ item.name }}" 
  with_items: '{{ nginx_site_removal_sites_to_remove }}'

- name: "Ensure NginX service is up"
  service:
    name: nginx 
    state: started 
    enabled: yes  

- name: "Restart NginX to make sure new configuration is active"
  service:
    name: nginx 
    state: restarted 
    enabled: yes  


